spring:
  application:
    name: fido2
  datasource:
    url: jdbc:h2:mem:fido2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
memo:
  storage: db
fido:
  rp-id: localhost
  rp-name: FIDO2 Demo
  origins:
    - http://localhost:8080
  challenge-ttl: PT5M
