create table fido_users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    display_name varchar(255) not null,
    user_handle bytea not null unique
);

create table fido_credentials (
    id bigint generated by default as identity primary key,
    user_id bigint not null references fido_users(id),
    credential_id bytea not null unique,
    public_key_cose bytea not null,
    signature_count bigint not null,
    last_authenticated_at timestamp with time zone
);

create table fido_ceremonies (
    id uuid primary key,
    type varchar(32) not null,
    username varchar(255),
    request_json clob not null,
    expires_at timestamp with time zone not null,
    state varchar(32) not null,
    consumed_at timestamp with time zone
);

create index idx_fido_ceremonies_expiry on fido_ceremonies(expires_at);
